ignoreErrors = ["error-missing-instagram-accesstoken"]
DefaultContentLanguage = "id"
author = "Ozi Saputra "
baseURL = "https://banjarnegara.pages.dev/"
copyright = "Copyright © 2020–2022, Wonderful Banjarnegara; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "id"
paginate = 3
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "Wonderful Banjarnegara "
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "image-credit"
name = "Image Credit"
url = "/image-credit/"
weight = 20
[params]
description = "Jelejahi Keindahan Banjarnegara "
facebook = "https://facebook.com/ozip.cf"
github = "https://github.com/ozipoetra "
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com/bot_ozip"
[privacy.instagram]
disabled = true
simple = true
[privacy.twitter]
disabled = true
enableDNT = true
simple = true
[privacy.vimeo]
disabled = true
simple = true
[privacy.youtube]
disabled = true
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
